{% set name = "xdg" %}
{% set version = "3.0.2" %}
{% set sha256 = "7ce9fc52cee0f8e31d0beb0f29e102f23725c0c470aee447d907e1999ffda7b7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .
  skip: True  # [win]

requirements:
  build:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6

test:
  imports:
    - xdg

about:
  home: https://github.com/srstevenson/xdg
  license: ISC
  license_file: LICENCE
  summary: 'Variables defined by the XDG Base Directory Specification'

  description: |
      xdg is a tiny Python module which provides the variables defined by the XDG Base Directory Specification, to save you from 
      duplicating the same snippet of logic in every Python utility you write that deals with user cache, configuration, or data files. 
      It has no external dependencies and supports Python 2 and 3.

extra:
  recipe-maintainers:
    - kain88-de
