travis:
  secure:
    BINSTAR_TOKEN: F9q7hvGsVJC5a1corVes0tZOOIYFyjhHK9UNv69lrhgcMB5tE1xAvxoYxdVeFTWlObR/EqTle8b2ElGHStAtRBsuR1oQKEZ1FlpSsHlX4+5icKjY/SPn4zgEqFFHQmSvSctO2/XV1/fJ9GmrUK9pIkFniqmfcy2zZrqihts37xiiK4mwdPiLU/knB0a80SfEZiLXBCNpb3kWQBibDhJCVcp78IDOTCZ5ku1BfSxoPiEaGYZ7njjqjHIBZ3NDYn4RKUmttuEUvk0ZrwoliGm7XJixdh2/yUQ7mLT195paUQzQcWeAFEYoQ/3mrpU2JWLdYQJYP/oxpaYtQrljdXPAJ6KDi0y0YHwiPCHtAc4e5tutsfrMvpQr2bJVtw5yRGpfq5KGlY+vtkjlGHriPEjOBAoZC5H9se71PcGezfXg5/1WXSPGhMlXsHUAcSjVtDS2JbnaaKjosMeHcC57Kl3dK1nqP2yJYH9l1BCXs4sXIblpaRd7hBGb+DIeFT6Ygm+PPMuMiCVyfSbByd/ZADN6YzNEOe23aOwJP7Ui5rU4fnHgWql83LGJvVK2M6cIkH9aZwy1b9b7bZhmzWwEpmQnny5B3HZKO4EGHom+04k4s9dhIHbc1mF04bD8/tQj8sjxoXCvPR2X6OPKfKzANF/YhTtzQxNjvdyNATkZ2iR1rhk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
